name: "Pull Request Linter"
 
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
 
jobs:
  execute:
    name: pr-linter-job
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: pr-linter-step
      # TODO remove feature reference from self run or disable it
        # uses: A5100907/pr-linter@v1
        uses: A5100907/pr-linter@feature/SDO-3120
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title_regex: ^\[([A-Z0-9]{1,6}-[0-9]{1,6}|BF|MERGE)\] ([a-zA-Z0-9 \!\?\'\"\=\.\,\(\)\_\-\+\>\<\/\@\:\$\%\&\*\#])+$
